options:
  enable-metadata:
    type: boolean
    default: False
    description: "Set as True to enable metadata support"
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources
  plumgrid-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of PLUMgrid packages that needs to be installed
