options:
  enable-metadata:
    type: boolean
    default: False
    description: "Set as True to enable metadata support"
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources
  plumgrid-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of PLUMgrid packages that needs to be installed
  networking-plumgrid-version:
    default: null
    type: string
    description: |
       Provide the version of networking-plumgrid package that needs to be installed
  plumgrid-username:
    default: plumgrid
    type: string
    description: Username to access PLUMgrid Director
  plumgrid-password:
    default: plumgrid
    type: string
    description: Password to access PLUMgrid Director
  plumgrid-virtual-ip:
    default:
    type: string
    description: IP address of PLUMgrid Director
  # end of PLUMgrid configuration
  manage-neutron-plugin-legacy-mode:
    type: boolean
    default: False
    description: |
      If True neutron-api charm will install neutron packages for the plugin
      configured. Also needs to be set in neutron-api charm
